### ISSUE TITLE
Question: How were you gathering iOPS and other metrics?

### ISSUE THREAD

**Issue by stevengibbszions** [joshuarobinson/fio-kubernetes#2]
Question: How were you gathering iOPS and other metrics?

**Comment by stevengibbszions** [comment]
> Question: How were you gathering iOPS and other metrics?

Referring to this article:
https://joshua-robinson.medium.com/storage-benchmarking-with-fio-in-kubernetes-14cf29dc5375

**Comment by joshuarobinson** [comment]
Hi Steve, for my case, I trust the metrics reported from my storage system, so I'm using those. In my article I showed screenshots of a GUI, but more generally I use Prometheus and [this exporter](https://github.com/PureStorage-OpenConnect/pure-exporter) to gather metrics.
